import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  weight: "400",           
  variable: "--font-inter",
});

export const metadata = {
  title: "Deepseek - GreatStack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <AppContext.Provider>
    <html lang="en">
      <body className={`${inder.className} antialiased`}>
        {children}
      </body>
    </html>
    </AppContext.Provider>
    </ClerkProvider>
  );
}
