import { Inder } from "next/font/google";
import "./globals.css";

const inder = Inder({
  subsets: ["latin"],
  weight: "400",           
  variable: "--font-inder",
});

export const metadata = {
  title: "Deepseek - GreatStack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inder.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
